"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2026-03-28 01:57:08.793640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='viewer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deletion_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('USER_REQUEST', 'TTL_EXPIRY', 'RETENTION_POLICY', name='deletionreason'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ARLO_PERSONA', 'ARLO_VOICE', 'PIPELINE_THRESHOLD', 'ESCALATION_THRESHOLD', 'NOTIFICATION_DEFAULT', 'EMAIL_PREFILTER', 'SUMMARIZATION_PROMPT', 'FEATURE_FLAG', name='configcategory'), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_system_config_category_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('preferred_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_language', sa.Text(), server_default='en', nullable=False),
    sa.Column('voice_id', sa.Text(), server_default='arlo_default', nullable=False),
    sa.Column('pace_setting', sa.Text(), server_default='normal', nullable=False),
    sa.Column('warmth_level', sa.Text(), server_default='warm', nullable=False),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('quiet_start', sa.Time(), nullable=True),
    sa.Column('quiet_end', sa.Time(), nullable=True),
    sa.Column('checkin_time', sa.Time(), server_default=sa.text("'09:00'"), nullable=True),
    sa.Column('away_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('away_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('config_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ARLO_PERSONA', 'ARLO_VOICE', 'PIPELINE_THRESHOLD', 'ESCALATION_THRESHOLD', 'NOTIFICATION_DEFAULT', 'EMAIL_PREFILTER', 'SUMMARIZATION_PROMPT', 'FEATURE_FLAG', name='configcategory'), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['system_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_channel', sa.Enum('CAMERA_SCAN', 'EMAIL', 'MAIL_STATION', name='sourcechannel'), nullable=False),
    sa.Column('raw_text_ref', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('BILL', 'LEGAL', 'GOVERNMENT', 'MEDICAL', 'INSURANCE', 'FORM', 'JUNK', 'PERSONAL', 'UNKNOWN', name='documentclassification'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('urgency_level', sa.Enum('ROUTINE', 'NEEDS_ATTENTION', 'ACT_TODAY', 'URGENT', name='urgencylevel'), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spoken_summary', sa.Text(), nullable=True),
    sa.Column('card_summary', sa.Text(), nullable=True),
    sa.Column('routing_destination', sa.Enum('HOME', 'MY_HEALTH', 'BILLS', 'PLANS', name='routingdestination'), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'CLASSIFIED', 'SUMMARIZED', 'ROUTED', 'ACKNOWLEDGED', 'HANDLED', name='documentstatus'), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('retention_phase', sa.Enum('FULL', 'IMPORTANT_ONLY', 'METADATA_ONLY', name='retentionphase'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('MEDICATION', 'PROVIDER', 'APPOINTMENT', 'BILL', 'PREFERENCE', 'CONTACT_INFO', 'OTHER', name='memorycategory'), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('USER_INPUT', 'DOCUMENT_EXTRACTION', 'ONBOARDING', 'SYSTEM', name='memorysource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'key', name='uq_functional_memory_user_category_key')
    )
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dosage', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pharmacy', sa.Text(), nullable=True),
    sa.Column('prescriber', sa.Text(), nullable=True),
    sa.Column('refill_due_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('context_type', sa.Enum('MEDICATION', 'BILL', 'DOCUMENT', 'FORM', 'TRAVEL', 'CHECKIN', name='questioncontexttype'), nullable=False),
    sa.Column('context_ref_id', sa.UUID(), nullable=True),
    sa.Column('urgency_level', sa.Enum('ROUTINE', 'NEEDS_ATTENTION', 'ACT_TODAY', 'URGENT', name='urgencylevel'), nullable=False),
    sa.Column('escalation_threshold_hours', sa.Integer(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'ESCALATED', 'EXPIRED', name='questionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ERRAND', 'SHOPPING', 'TASK', 'GENERAL', name='todocategory'), nullable=False),
    sa.Column('source', sa.Enum('USER', 'ARLO_SUGGESTION', 'DOCUMENT', name='todosource'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trusted_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.Enum('FAMILY', 'CASE_WORKER', 'SUPPORT_COORDINATOR', 'GROUP_HOME_STAFF', 'PAID_SUPPORT', name='relationshiptype'), nullable=False),
    sa.Column('access_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='accesstier'), nullable=False),
    sa.Column('tier_3_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.Text(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('appointment_at', sa.DateTime(), nullable=False),
    sa.Column('travel_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('account_number_masked', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('reminder_set', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregiver_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trusted_contact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('VIEWED_DASHBOARD', 'RECEIVED_ALERT', 'TIER3_SESSION', name='caregiveraction'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['trusted_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('missed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_metrics')
    op.drop_table('medication_confirmations')
    op.drop_table('caregiver_activity_log')
    op.drop_table('bills')
    op.drop_table('appointments')
    op.drop_table('trusted_contacts')
    op.drop_table('todos')
    op.drop_table('questions_tracker')
    op.drop_table('medications')
    op.drop_table('functional_memory')
    op.drop_table('documents')
    op.drop_table('config_audit_log')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('deletion_audit_log')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
